Update ReadMe.md
Laura-Novich-OBW/student-showcase pull request #100
Opened 2022-11-30 16:25 UTC by mindys360

2022-12-01 07:44 UTC, Laura-Novich-OBW reviewed
small improvement - adding mailto: to your email will open your default email app and populate the TO field with your email address.

2022-12-01 07:44 UTC, Laura-Novich-OBW commented on student-work/2022/Mindy-Steen/ReadMe.md
> +[LinkedIn](https://www.linkedin.com/in/mindysteen360/) | [Email](mindys360@gmail.com)
```suggestion
[LinkedIn](https://www.linkedin.com/in/mindysteen360/) | [Email](mailto:mindys360@gmail.com) 
```

2022-12-01 07:44 UTC, Laura-Novich-OBW commented
Please look at the small change
and approve or reject

2022-12-01 07:45 UTC, Laura-Novich-OBW requested changes
please look at the comment and either accept or reject the changes
looking good!

2022-12-10 15:54 UTC, lsnovich commented
Seems to me that this change was already done in the PR I just merged. 
https://github.com/Laura-Novich-OBW/student-showcase/pull/101
If this is not the case let me know and I'll re-open this one. \
Otherwise, if the PR#101 is correct let this one stay closed

2022-12-10 15:54 UTC, closed without merging