Update readme.md
Laura-Novich-OBW/student-showcase pull request #11
Opened 2022-02-08 19:05 UTC by JoeWainer

Updated readme.md with my resume

2022-02-12 18:57 UTC, lsnovich requested changes

2022-02-12 18:57 UTC, lsnovich commented on student-work/joe-wainer/readme.md
> +_March 2022 - Present_
for all dashes which are not bullets
please use &ndash; instead of - 
it makes for cleaner code.

2022-02-12 18:57 UTC, lsnovich commented on student-work/joe-wainer/readme.md
> +**Ashmole Science Academy, London**
information missing?

2022-02-28 07:32 UTC, JoeWainer commented
Hi @lsnovich  do I need to do anything else?

2022-03-10 18:37 UTC, merged