Create flowchart-bedtime-routine.md
Laura-Novich-OBW/student-showcase pull request #116
Opened 2023-01-25 22:07 UTC by Yael0508

2023-01-27 11:08 UTC, Laura-Novich-OBW requested changes
consider the changes I made

2023-01-27 11:08 UTC, Laura-Novich-OBW commented on student-work/2022/Yael-Lachman/flowchart-bedtime-routine.md
> +  A(Start)-->B[Eat supper]
```suggestion
  A((Start))-->B[Eat supper]
```

2023-01-27 11:08 UTC, Laura-Novich-OBW commented on student-work/2022/Yael-Lachman/flowchart-bedtime-routine.md
> +  I--No-->K[Put clothes in washing machine]
```suggestion
  I--No-->K[Put clothes in washing machine]
  K-->J
```

2023-01-27 11:08 UTC, Laura-Novich-OBW commented on student-work/2022/Yael-Lachman/flowchart-bedtime-routine.md
> +  K-->L
```suggestion

```

2023-01-27 11:08 UTC, Laura-Novich-OBW commented on student-work/2022/Yael-Lachman/flowchart-bedtime-routine.md
> +  M-->N(End)
```suggestion
  M-->N((End))
```

2023-01-28 22:13 UTC, Yael0508 commented
Committed all your changes, thanks

2023-01-30 18:56 UTC, merged