Updated readme.md file
Laura-Novich-OBW/student-showcase pull request #12
Opened 2022-02-09 00:05 UTC by miriam1986

Content changed to a CV based on my Linked In Profile:
- added my profile photo
- added About section
- added Experience section
- added Education section
- added Skills section
- added Languages section

2022-02-09 00:06 UTC, miriam1986 commented
Content changed to a CV based on my Linked In Profile:

added my profile photo
added About section
added Experience section
added Education section
added Skills section
added Languages section

2022-02-12 18:46 UTC, Laura-Novich-OBW commented on student-work/miriam-rosenberg/readme.md
> +Mar 2021-Present
```suggestion
Mar 2021 &ndash; Present  
```

2022-02-12 18:48 UTC, Laura-Novich-OBW requested changes

2022-02-12 18:48 UTC, Laura-Novich-OBW commented on student-work/miriam-rosenberg/readme.md
> +Mar 2021-Present
Use this in all dates. While the dash is fine, this is cleaner code as it will never create an issue where the compiler doesn't understand.

2022-02-13 13:04 UTC, miriam1986 commented
All changes have been made as suggested. Thank you

2022-02-13 13:05 UTC, miriam1986 commented
Please approve so that I can merge the branch

2022-02-21 17:43 UTC, Laura-Novich-OBW approved these changes
Looks great! Please merge. If there are issues, I'll let you know.

2022-02-22 13:16 UTC, miriam1986 commented
@Laura-Novich-OBW ,
I don't have an option for merging this PR. 

![Merge](https://user-images.githubusercontent.com/92327775/155139882-0cd8414b-93ca-4d6e-b364-10f6ccb17f87.JPG)

2022-03-01 19:23 UTC, merged