Create README.md
Laura-Novich-OBW/student-showcase pull request #128
Opened 2023-04-15 09:10 UTC by delas6006

2023-04-18 06:32 UTC, Laura-Novich-OBW requested changes

2023-04-18 06:32 UTC, Laura-Novich-OBW commented on student-work/2022/Debbie-Mankowitz/api-final-project/README.md
> +This is the new APP for customers for online orders for General Putnam Motel Diner (GPMD).
```suggestion
This API is for creating a new APP for General Putnam Motel Diner (GPMD).  Customers of GPMD can use the app to order food. This initial offering is a Proof of Concept (PoC). 
```

2023-04-18 06:32 UTC, Laura-Novich-OBW commented on student-work/2022/Debbie-Mankowitz/api-final-project/README.md
> +This App is intended for customers as a preliminary version for take-out hamburger meals.
```suggestion
It is limited in scope and the preliminary version only supports creating a take-out hamburger meal order.
```

2023-04-18 06:32 UTC, Laura-Novich-OBW commented on student-work/2022/Debbie-Mankowitz/api-final-project/README.md
> +If the App becomes popular and easy to use then GPMD will extend their APP to include other offerings on their menu.
```suggestion
If the PoC is accepted, the App can be expanded so that GPMD can extend their APP to include other offerings on their menu.
```

2023-05-03 06:03 UTC, Laura-Novich-OBW commented on student-work/2022/Debbie-Mankowitz/api-final-project/README.md
> +This is the new APP for customers for online orders for General Putnam Motel Diner (GPMD).
Debbie if you like the change I am suggesting click the "Commit Suggestion" button and commit the change.

2023-05-03 06:11 UTC, delas6006 commented
Thank you so much, Laura

2023-05-03 06:12 UTC, delas6006 commented
Thank you so much, Laura

2023-05-03 06:12 UTC, closed without merging

2023-05-03 06:13 UTC, delas6006 commented
Hi Laura

I can only say thank you for being such a huge support.

Best regards

Debbie


On Wed, May 3, 2023 at 9:04 AM Laura-Novich-OBW ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In student-work/2022/Debbie-Mankowitz/api-final-project/README.md
> <https://github.com/Laura-Novich-OBW/student-showcase/pull/128#discussion_r1183269098>
> :
>
> > @@ -0,0 +1,25 @@
> +# Hamburger API DOC
> +This is the new APP for customers for online orders for General Putnam Motel Diner (GPMD).
>
> Debbie if you like the change I am suggesting click the "Commit
> Suggestion" button and commit the change.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Laura-Novich-OBW/student-showcase/pull/128#discussion_r1183269098>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2AKUUY5C5AQFQCRK7CS43LXEHYNLANCNFSM6AAAAAAW7JFDFQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>