Update readme.md
Laura-Novich-OBW/student-showcase pull request #140
Opened 2023-07-08 22:52 UTC by jrtechcomm

Assignment 7 ready for review by Laura. Unsure of where to add link to portfolio, as portfolio is not ready to show yet. GitHub projects will also be added in the future.

2023-07-11 06:39 UTC, Laura-Novich-OBW commented on student-work/2022/Jason-Rosenberg/readme.md
> +**JASON CHAIM ROSENBERG**
```suggestion
# JASON CHAIM ROSENBERG
```

2023-07-11 06:46 UTC, Laura-Novich-OBW requested changes

2023-07-11 06:46 UTC, Laura-Novich-OBW commented on student-work/2022/Jason-Rosenberg/readme.md
> +**JASON CHAIM ROSENBERG**
This should be H1

2023-07-11 06:46 UTC, Laura-Novich-OBW commented on student-work/2022/Jason-Rosenberg/readme.md
> +# **Skills Summary**
```suggestion
# Skills Summary
```

2023-07-11 06:46 UTC, Laura-Novich-OBW commented on student-work/2022/Jason-Rosenberg/readme.md
> +# **Skills Summary**
No need for bold as it is included in the style.

2023-07-11 06:46 UTC, Laura-Novich-OBW commented on student-work/2022/Jason-Rosenberg/readme.md
> +# **Skills Summary**
Change the remaining headings, remove the ** asterisks.

2023-07-11 06:46 UTC, Laura-Novich-OBW commented on student-work/2022/Jason-Rosenberg/readme.md
> +##
```suggestion
```

2023-07-11 06:46 UTC, Laura-Novich-OBW commented on student-work/2022/Jason-Rosenberg/readme.md
> +Edited US Patent applications for electrical engineering professor emeritus, Chair of Computer Architecture, University of Alabama, and Auburn University. Handled business and legal communication in
```suggestion
Edited US Patent applications for electrical engineering professor emeritus, Chair of Computer Architecture at the University of Alabama, and Auburn University. Handled business and legal communication in writing, on the phone, and in person. Worked with large Intellectual Property Law Firms in Atlanta and Irvine to prosecute multiple U.S. Patent applications that were granted by the USPTO. Worked on an IP enforcement case vs. Texas Instruments. Sold my share of the partnership in 2014 at a profit.
```

2023-07-11 06:46 UTC, Laura-Novich-OBW commented
Some changes need to be made as per comments within. 
Make the changes and resubmit. 
You're almost there!

2023-07-24 20:27 UTC, jrtechcomm reviewed
Please re-read and approve. One change may not have worked.

2023-07-30 17:51 UTC, merged