Update readme.md
Laura-Novich-OBW/student-showcase pull request #149
Opened 2023-10-25 09:37 UTC by NatanyaDC

Added my CV

2023-10-25 09:55 UTC, lsnovich commented on student-work/2023/Natanya-DaCosta/readme.md
> +Created content for a non-profit.
```suggestion
* Created content for a non-profit.  
```

2023-10-25 09:56 UTC, lsnovich commented on student-work/2023/Natanya-DaCosta/readme.md
> +Created content for a non-profit.
Please add bullets like this to the rest of the content that needs it

2023-10-25 18:02 UTC, Laura-Novich-OBW commented on student-work/2023/Natanya-DaCosta/readme.md
> +enatanyadc@gmail.com
```suggestion
✉️ enatanyadc@gmail.com  
```

2023-10-25 18:03 UTC, Laura-Novich-OBW requested changes
please make the change

2023-10-30 07:47 UTC, lsnovich approved these changes
Looks great!
Merging now. Please take a screenshot of the merge message and upload it to Google Classroom.

2023-10-30 07:48 UTC, Laura-Novich-OBW approved these changes

2023-10-30 07:48 UTC, merged