Update readme.md
Laura-Novich-OBW/student-showcase pull request #160
Opened 2023-10-25 23:40 UTC by hafarfur

First edit of my readme

2023-10-28 16:40 UTC, Laura-Novich-OBW requested changes
Please add your CV, it doesn't have to be the same as your LinkedIn profile. 
If you do not have one at all this is a bigger issue.

2023-10-28 16:40 UTC, Laura-Novich-OBW commented on student-work/2023/Max-Zingerman/readme.md
> +# Max's readme file
```suggestion
# Max's Readme File 
```

2023-10-28 16:40 UTC, Laura-Novich-OBW commented on student-work/2023/Max-Zingerman/readme.md
> +This is going to be my readme file
```suggestion
This is going to be my readme file.  
```

2023-10-28 16:40 UTC, Laura-Novich-OBW commented on student-work/2023/Max-Zingerman/readme.md
> +I don't have a portfolio yet nor a LinkedIn account
```suggestion
I don't have a portfolio yet, nor do I have a LinkedIn account.  
```

2023-10-28 16:40 UTC, Laura-Novich-OBW commented on student-work/2023/Max-Zingerman/readme.md
> +Can't think of something to add here now. I'll add things here in the future.
```suggestion
I can't think of something to add here now. I'll add things here in the future.   
```

2024-01-03 18:10 UTC, hafarfur commented
PR

2024-01-04 12:44 UTC, Laura-Novich-OBW approved these changes

2024-01-04 12:44 UTC, Laura-Novich-OBW commented
much better!

2024-01-04 12:44 UTC, merged