Diagram assignment
Laura-Novich-OBW/student-showcase pull request #174
Opened 2023-12-20 13:25 UTC by yossimyhill

Hi Laura.
Here are the diagrams you asked for.
Hope they are good:)

2023-12-27 18:28 UTC, lsnovich commented
Hi Yossi
Please make all lines in the flowchart solid lines. 
Thanks!

2024-01-06 16:08 UTC, lsnovich commented on Morning_Schedule_Flowchart.md
> +D -.Before 06:00.-> E[Go to Mikva];
```suggestion
D --Before 06:00--> E[Go to Mikva];
```

2024-01-06 16:11 UTC, lsnovich requested changes
please accept or reject changes

2024-01-06 16:11 UTC, lsnovich commented on Morning_Schedule_Flowchart.md
> +D -.After 06:00.-> F{Is it before 06:30?};
```suggestion
D --After 06:00--> F{Is it before 06:30?};
```

2024-01-06 16:11 UTC, lsnovich commented on Morning_Schedule_Flowchart.md
> +F-.Yes.->G;
```suggestion
F--Yes-->G;
```

2024-01-06 16:11 UTC, lsnovich commented on Morning_Schedule_Flowchart.md
> +F-.No.->H[Help the kids get ready for school];
```suggestion
F--No-->H[Help the kids get ready for school];
```

2024-01-06 16:11 UTC, lsnovich commented on Morning_Schedule_Flowchart.md
> +K -.Yes.-> M{Is there time to clean the house before leaving?};
```suggestion
K --Yes--> M{Is there time to clean the house before leaving?};
```

2024-01-06 16:11 UTC, lsnovich commented on Morning_Schedule_Flowchart.md
> +K -.No.-> L[Finish getting them ready, bring them to school];
```suggestion
K --No--> L[Finish getting them ready, bring them to school];
```

2024-01-06 16:11 UTC, lsnovich commented on Morning_Schedule_Flowchart.md
> +M-.Yes.->N[Clean the house];
```suggestion
M--Yes-->N[Clean the house];
```

2024-01-06 16:11 UTC, lsnovich commented on Morning_Schedule_Flowchart.md
> +M-.No.->O[Walk towards the nearest number 12 bus stop];
```suggestion
M--No-->O[Walk towards the nearest number 12 bus stop];
```

2024-01-06 16:11 UTC, lsnovich commented on Morning_Schedule_Flowchart.md
> +Q-.Yes.->R[Get off the 12 at Hagalil, wait for the 26, go onto the 26];
```suggestion
Q--Yes-->R[Get off the 12 at Hagalil, wait for the 26, go onto the 26];
```

2024-01-06 16:11 UTC, lsnovich commented on Morning_Schedule_Flowchart.md
> +Q-.No.->T[Stay on the 12 until the Highway 40 stop, get off at that stop];
```suggestion
Q--No-->T[Stay on the 12 until the Highway 40 stop, get off at that stop];
```

2024-01-06 16:14 UTC, lsnovich reviewed
The apartment rental and morning schedule files are in the wrong location.
Please move them to 
student-work/2023/Yosef-Myhill/diagrams

2024-01-06 16:15 UTC, lsnovich commented
Good start! If my comments or changes are not clear let me know.

2024-01-27 16:49 UTC, Laura-Novich-OBW approved these changes

2024-01-27 16:49 UTC, merged