CV readme
Laura-Novich-OBW/student-showcase pull request #184
Opened 2024-01-08 23:29 UTC by AlanFFM

Hi there! This is for one of the assignments. Cheers!

2024-01-09 10:27 UTC, Laura-Novich-OBW commented on student-work/2023/Alan-Bariman/readme.md
> +•	Mastery of: Excel, Word, Photohosop, Illustrator, Latik, MasterCam, Fusion360, Lightroom, and Blender.<br />
All bullets are as follows

```* text ``` so it becomes
* text
* text

2024-01-09 10:28 UTC, Laura-Novich-OBW commented on student-work/2023/Alan-Bariman/readme.md
> +•	Mastery of: Excel, Word, Photohosop, Illustrator, Latik, MasterCam, Fusion360, Lightroom, and Blender.<br />
one space between the bullet and the text

2024-01-09 10:29 UTC, Laura-Novich-OBW commented on student-work/2023/Alan-Bariman/readme.md
> +ALAN BARIMAN
Consider using headings

```# Heading``` becomes
# Heading

2024-01-09 10:32 UTC, Laura-Novich-OBW commented
Hi Alan, nice job. 
I strongly suggest you use the Markdown cheat sheets I provided in Google Classroom and make sure that your markdown is clean and highly organized. 

While you don't need to use massive amounts of HTML, you should use styles and formats which make the page appealing to a potential manager.

2024-01-23 09:28 UTC, Laura-Novich-OBW requested changes
please address the comments

2024-01-25 14:52 UTC, AlanFFM commented
Hi. returned from Mexico. Getting on this today.

2024-01-28 16:44 UTC, Laura-Novich-OBW approved these changes

2024-01-28 16:44 UTC, merged