Created GitHub Environment for Final API Project
Laura-Novich-OBW/student-showcase pull request #185
Opened 2024-01-09 10:49 UTC by NatanyaDC

Created API Final Project, Get file, and Post file.

2024-01-17 19:02 UTC, NatanyaDC commented
Changes made!

2024-01-23 09:27 UTC, Laura-Novich-OBW requested changes
small change to the GET file, keep going you got this!!

2024-01-23 09:27 UTC, Laura-Novich-OBW commented on student-work/2023/Natanya-DaCosta/api-final-project/get.md
> +
Fot GET responses, you do not need a value column. The value will change depending on what actions are done and what values are in the database. 

Please remove this column

2024-01-23 10:10 UTC, NatanyaDC commented
Made requested change. Took out the value column in the table of the Get Response.

2024-01-27 16:38 UTC, lsnovich approved these changes

2024-01-27 16:38 UTC, lsnovich commented
Natanya, nice job!

2024-01-27 16:39 UTC, Laura-Novich-OBW approved these changes

2024-01-27 16:39 UTC, merged

2024-01-27 16:43 UTC, Laura-Novich-OBW commented
Please submit to Google Classroom