api project completed - hopefully!
Laura-Novich-OBW/student-showcase pull request #187
Opened 2024-01-17 20:04 UTC by ShlomoRBarron

2024-01-23 09:22 UTC, Laura-Novich-OBW requested changes
one small change to two files, but otherwise amazing!

2024-01-23 09:22 UTC, Laura-Novich-OBW commented on student-work/2023/Shlomo-Bar-On/api-final-project/get.md
> +> Explore other templates from [The Good Docs Project](https://thegooddocsproject.dev/). Use our [feedback form](https://thegooddocsproject.dev/feedback/?template=API%20reference) to give feedback on
```suggestion
> Explore other templates from [The Good Docs Project](https://thegooddocsproject.dev/). Use the [feedback form](https://thegooddocsproject.dev/feedback/?template=API%20reference) to give feedback on this template.
```

2024-01-23 09:22 UTC, Laura-Novich-OBW commented on student-work/2023/Shlomo-Bar-On/api-final-project/post.md
> +> Explore other templates from [The Good Docs Project](https://thegooddocsproject.dev/). Use our [feedback form](https://thegooddocsproject.dev/feedback/?template=API%20reference) to give feedback on
```suggestion
> Explore other templates from [The Good Docs Project](https://thegooddocsproject.dev/). Use the [feedback form](https://thegooddocsproject.dev/feedback/?template=API%20reference) to give feedback on this template.
```

2024-01-23 12:25 UTC, ShlomoRBarron commented
Changes committed.

Ready for merge.

> On 23 Jan 2024, at 11:22, Laura-Novich-OBW ***@***.***> wrote:
> 
> 
> @Laura-Novich-OBW requested changes on this pull request.
> 
> one small change to two files, but otherwise amazing!
> 
> In student-work/2023/Shlomo-Bar-On/api-final-project/get.md <https://github.com/Laura-Novich-OBW/student-showcase/pull/187#discussion_r1462964060>:
> 
> > +|--------|--------|----------------------------------|
> +|orderNum|Integer|The number of the order for which this bill has been generated.
> +|timestamp|Date|The time the order was placed.
> +|Item1|JSON object|The first menu item ordered.
> +|ItemOrdered|Nested JSON object|Detail of Item1
> +|type|String|There's only one type for this POC
> +|Cost|Float|Cost of burgerMeal
> +|Item2|JSON object|The side order menu item ordered.
> +|ItemOrdered|Nested JSON object|Detail of Item2
> +|type|String|pommeFritesMedium
> +|Cost|Float|Cost of side order type
> +
> +
> +---
> +
> +> Explore other templates from [The Good Docs Project](https://thegooddocsproject.dev/). Use our [feedback form](https://thegooddocsproject.dev/feedback/?template=API%20reference) to give feedback on this template.
> ⬇️ Suggested change
> -> Explore other templates from [The Good Docs Project](https://thegooddocsproject.dev/). Use our [feedback form](https://thegooddocsproject.dev/feedback/?template=API%20reference) to give feedback on this template.
> +> Explore other templates from [The Good Docs Project](https://thegooddocsproject.dev/). Use the [feedback form](https://thegooddocsproject.dev/feedback/?template=API%20reference) to give feedback on this template.
> In student-work/2023/Shlomo-Bar-On/api-final-project/post.md <https://github.com/Laura-Novich-OBW/student-showcase/pull/187#discussion_r1462964691>:
> 
> > +	"sideDish": "coleslawLarge",
> +	"softDrink": "coke",
> +	"ice": true,
> +	"server": "Brenda",
> +	"server_id":"aslkw0923CAE", 
> +	"cook": "Lou", 
> +	"cook_id": "l2j23j9LKJsd",
> +	"price_base": "10.99", 
> +	"price_add": "8.00", 
> +	"price_total": "18.99" 
> +	}
> +}
> +```
> +---
> +
> +> Explore other templates from [The Good Docs Project](https://thegooddocsproject.dev/). Use our [feedback form](https://thegooddocsproject.dev/feedback/?template=API%20reference) to give feedback on this template.
> ⬇️ Suggested change
> -> Explore other templates from [The Good Docs Project](https://thegooddocsproject.dev/). Use our [feedback form](https://thegooddocsproject.dev/feedback/?template=API%20reference) to give feedback on this template.
> +> Explore other templates from [The Good Docs Project](https://thegooddocsproject.dev/). Use the [feedback form](https://thegooddocsproject.dev/feedback/?template=API%20reference) to give feedback on this template.
> —
> Reply to this email directly, view it on GitHub <https://github.com/Laura-Novich-OBW/student-showcase/pull/187#pullrequestreview-1838260440>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/BDQY7S67M7KDCRYFOCFVRSTYP56ONAVCNFSM6AAAAABB7D5TIWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMZYGI3DANBUGA>.
> You are receiving this because you authored the thread.
>

2024-01-27 16:40 UTC, Laura-Novich-OBW approved these changes

2024-01-27 16:40 UTC, merged

2024-01-27 16:42 UTC, Laura-Novich-OBW commented
nice job please submit to Google Classroom