API project files
Laura-Novich-OBW/student-showcase pull request #203
Opened 2024-01-29 20:34 UTC by Schnee18

First draft of GET, POST, and README files for the API final project.

2024-02-24 16:46 UTC, Laura-Novich-OBW requested changes
small changes but otherwise looking good!

2024-02-24 16:46 UTC, Laura-Novich-OBW commented on student-work/2023/Sharon-Schnee/api-final-project/post.md
> +```
```suggestion
``` JSON
```

2024-02-24 16:46 UTC, Laura-Novich-OBW commented on student-work/2023/Sharon-Schnee/api-final-project/readme.md
> +1. [Getting started](#getting-started)
```suggestion
[Getting started](#getting-started)
```

2024-02-24 16:46 UTC, Laura-Novich-OBW commented on student-work/2023/Sharon-Schnee/api-final-project/readme.md
> +2. [Authentication](#authentication)
```suggestion
[Authentication](#authentication)
```

2024-02-24 16:46 UTC, Laura-Novich-OBW commented on student-work/2023/Sharon-Schnee/api-final-project/readme.md
> +3. [API reference](#API-reference)
```suggestion
[API reference](#API-reference)
```

2024-02-24 16:46 UTC, Laura-Novich-OBW commented on student-work/2023/Sharon-Schnee/api-final-project/readme.md
> +
## Additional Information

2024-02-24 16:46 UTC, Laura-Novich-OBW commented on student-work/2023/Sharon-Schnee/api-final-project/readme.md
> +
@Schnee18 - consider moving this to the end of the page

2024-02-25 07:38 UTC, Schnee18 commented on student-work/2023/Sharon-Schnee/api-final-project/readme.md
> +
Thanks for the feedback! Two questions:

1. What should I move to the end of the page? The heading "Hamburger POC API Guide"? 
2. Also for the links to different parts of the readme, I wanted it in a list. Did you just want the numbers taken out, or should it not be in a list?

2024-03-01 08:04 UTC, Laura-Novich-OBW commented on student-work/2023/Sharon-Schnee/api-final-project/post.md
> +drink | boolean  | N | With or without ice. Options include true=with ice, false=without ice. | true |
```suggestion
ice | boolean  | N | With or without ice. Options include true=with ice, false=without ice. | true |
```

2024-03-01 08:10 UTC, Laura-Novich-OBW commented on student-work/2023/Sharon-Schnee/api-final-project/post.md
> +--header 'Authorization: Bearer ImahFWLZWFdD8VVcUtIED2YuOjPFlZpldQTE5tUqKdv'
Lines 55 and 56 are examples for authorization (using HTTP headers) so if you want to include it in that section you can.

2024-03-11 14:16 UTC, Laura-Novich-OBW commented on student-work/2023/Sharon-Schnee/api-final-project/readme.md
> +
the links to additional information should be moved to the end of the page

2024-03-13 06:13 UTC, Laura-Novich-OBW approved these changes

2024-03-13 06:13 UTC, merged