Api project
Laura-Novich-OBW/student-showcase pull request #208
Opened 2024-01-30 15:33 UTC by RinaSol

Adding my three files for Review.

2024-02-24 17:13 UTC, Laura-Novich-OBW requested changes
Please make the following changes

2024-02-24 17:13 UTC, Laura-Novich-OBW commented on GET.md
> +curl -X GET "http://URL/tableNo?id=99"
```suggestion
```curl -X GET "http://URL/tableNo?id=99"```
```

2024-02-24 17:13 UTC, Laura-Novich-OBW commented on POST.md
> +|Drink size|medium, large or extra large|which size would the client like for his drink that is from the fountain and not a bottled drink|medium|string|O|
```suggestion
|Drink size|medium, large, or extra large|fountain drink size|medium|string|O|
```

2024-02-25 01:09 UTC, RinaSol commented
Both GET.md and POST.md updated as requested

2024-02-25 01:10 UTC, RinaSol commented
Both GET.md and POST.md updated as requested

2024-02-25 01:19 UTC, RinaSol commented on GET.md
> +timestamp | timestamp | The time the meal was ordered.
Update done

2024-02-25 01:19 UTC, RinaSol commented on GET.md
> +Cost | Float | Cost of the meal
Update completed

2024-02-25 01:20 UTC, RinaSol commented on GET.md
> +curl -X GET "http://URL/tableNo?id=99"
Update completed

2024-02-25 01:20 UTC, RinaSol commented on POST.md
> +|Drink size|medium, large or extra large|which size would the client like for his drink that is from the fountain and not a bottled drink|medium|string|O|
Update to POST file completed.

2024-03-11 14:14 UTC, merged