CV readme added
Laura-Novich-OBW/student-showcase pull request #210
Opened 2024-02-15 05:43 UTC by hafarfur

This PR has the markdown version of my CV. It is the "Markup makeup" assignment.

2024-02-16 09:39 UTC, Laura-Novich-OBW requested changes
Nice start!

2024-02-16 09:39 UTC, Laura-Novich-OBW commented on student-work/2023/Max-Zingerman/api-final-project/get.md
> +| Item1 | Ordered item No 1 | 'ItemOrdered' object |
```suggestion
| Item1 | Ordered item No 1 | object |
```

2024-02-16 09:39 UTC, Laura-Novich-OBW commented on student-work/2023/Max-Zingerman/api-final-project/get.md
> +| Item2 | Ordered item No 2. Optional | 'ItemOrdered' object |
```suggestion
| Item2 | Ordered item No 2. Optional | object |
```

2024-02-16 09:39 UTC, Laura-Novich-OBW commented on student-work/2023/Max-Zingerman/api-final-project/get.md
> +| Item3 | Ordered item No 3. Optional | 'ItemOrdered' object |
```suggestion
| Item3 | Ordered item No 3. Optional | object |
```

2024-02-16 09:39 UTC, Laura-Novich-OBW commented on student-work/2023/Max-Zingerman/api-final-project/get.md
> +| Item4 | Ordered item No 4. Optional | 'ItemOrdered' object |
```suggestion
| Item4 | Ordered item No 4. Optional | object |
```

2024-02-16 09:39 UTC, Laura-Novich-OBW commented on student-work/2023/Max-Zingerman/api-final-project/get.md
> +| Item5 | Ordered item No 5. Optional | 'ItemOrdered' object |
```suggestion
| Item5 | Ordered item No 5. Optional | object |
```

2024-02-16 09:39 UTC, Laura-Novich-OBW commented on student-work/2023/Max-Zingerman/api-final-project/get.md
> +| Item6 | Ordered item No 6. Optional | 'ItemOrdered' object |
```suggestion
| Item6 | Ordered item No 6. Optional | object |
```

2024-02-16 09:39 UTC, Laura-Novich-OBW commented on student-work/2023/Max-Zingerman/api-final-project/post.md
> +### Parameters:
```suggestion

### Parameters:
```

2024-02-16 09:39 UTC, Laura-Novich-OBW commented on student-work/2023/Max-Zingerman/api-final-project/readme.md
> +
please applythe above comments to all flowcharts.

2024-02-16 09:40 UTC, Laura-Novich-OBW commented
please make the necessary changes

2024-02-18 01:27 UTC, hafarfur commented on student-work/2023/Max-Zingerman/api-final-project/readme.md
> +
I've tried to keep it as simple as possible since mermaid doesn't render complex diagrams well. I'll create some Draw.io flowchart diagrams instead and submit them in a separate PR.

2024-02-18 01:40 UTC, hafarfur commented
Hi Laura,
I've commited all requested changes.
As for the diagrams, I've tried to keep it as simple as possible since mermaid doesn't render complex diagrams well. I'll try to create some Draw.io flowchart diagrams instead and submit them in a separate PR.

2024-02-19 02:06 UTC, hafarfur commented
I made all the changes you suggested, and fixed the diagrams.
Please merge this PR.
Thanks
Max

2024-02-24 16:29 UTC, Laura-Novich-OBW commented
I am going to merge this. It contains several assignments together. Please check that the merge didn't change anything and please sync

2024-02-24 16:29 UTC, Laura-Novich-OBW approved these changes

2024-02-24 16:30 UTC, merged