Jacob Sacks - API Project
Laura-Novich-OBW/student-showcase pull request #217
Opened 2024-05-22 17:04 UTC by jsacks2

This is the first draft of my API assignment. I hope it's good 🤞

2024-05-26 06:08 UTC, Laura-Novich-OBW reviewed
Fantastic start.
small comments. 
Please apply or reject

2024-05-26 06:08 UTC, Laura-Novich-OBW commented on student-work/2023/Jacob-Sacks/API-final-project/get.md
> +
```suggestion
For takeout orders the table number is 99.
```

2024-05-26 06:08 UTC, Laura-Novich-OBW commented on student-work/2023/Jacob-Sacks/API-final-project/get.md
> +```
```suggestion

``` none
```

2024-05-26 06:08 UTC, Laura-Novich-OBW commented on student-work/2023/Jacob-Sacks/API-final-project/get.md
> +```
```suggestion
``` json
```

2024-05-26 06:08 UTC, Laura-Novich-OBW commented on student-work/2023/Jacob-Sacks/API-final-project/get.md
> +| 200         | Success        | Bill was successfully printed |
```suggestion
| 200         | Success        | Request for the bill was successfully executed|
```

2024-05-26 06:08 UTC, Laura-Novich-OBW commented on student-work/2023/Jacob-Sacks/API-final-project/post.md
> +```
```suggestion
```

```

2024-05-26 06:08 UTC, Laura-Novich-OBW commented on student-work/2023/Jacob-Sacks/API-final-project/post.md
> +```
```suggestion
``` json
```

2024-05-26 06:08 UTC, Laura-Novich-OBW commented on student-work/2023/Jacob-Sacks/API-final-project/post.md
> +| 200         | Success        | Meal was successfully received and sent to the kitchen |
```suggestion
| 200         | Success        | Meal request was successfully received and sent to the kitchen |
```

2024-05-26 06:09 UTC, Laura-Novich-OBW requested changes
see comments within

2024-05-28 06:26 UTC, jsacks2 commented
I just committed the suggested changes. Thanks for the quick feedback.

2024-06-14 07:46 UTC, Laura-Novich-OBW approved these changes

2024-06-14 07:46 UTC, merged