API final project
Laura-Novich-OBW/student-showcase pull request #44
Opened 2022-04-04 05:43 UTC by michaelfelsenthal

2022-04-06 16:13 UTC, Laura-Novich-OBW reviewed
please remove the empty lines which are all over this file.
If you want some white space one or two lines is fine.
In your code sample, however, there cannot be any empty lines.

2022-04-06 16:13 UTC, Laura-Novich-OBW commented on student-work/michael-felsenthal/api-final-project/readme.md
> +
```suggestion
```

2022-04-06 16:13 UTC, Laura-Novich-OBW commented on student-work/michael-felsenthal/api-final-project/readme.md
> +
```suggestion
```

2022-04-06 16:13 UTC, Laura-Novich-OBW commented on student-work/michael-felsenthal/api-final-project/readme.md
> +
```suggestion
```

2022-04-06 16:13 UTC, Laura-Novich-OBW commented on student-work/michael-felsenthal/api-final-project/readme.md
> +
```suggestion
```

2022-04-06 16:13 UTC, Laura-Novich-OBW commented on student-work/michael-felsenthal/api-final-project/readme.md
> +
```suggestion
```

2022-04-06 16:13 UTC, Laura-Novich-OBW commented on student-work/michael-felsenthal/api-final-project/readme.md
> +
```suggestion
```

2022-04-06 16:13 UTC, Laura-Novich-OBW commented on student-work/michael-felsenthal/api-final-project/readme.md
> +
```suggestion
```

2022-04-06 16:13 UTC, Laura-Novich-OBW commented on student-work/michael-felsenthal/api-final-project/readme.md
> +
```suggestion
```

2022-04-06 16:13 UTC, Laura-Novich-OBW commented on student-work/michael-felsenthal/api-final-project/readme.md
> +
```suggestion
```

2022-04-06 16:13 UTC, Laura-Novich-OBW commented on student-work/michael-felsenthal/api-final-project/readme.md
> +
```suggestion
```

2022-04-06 16:13 UTC, Laura-Novich-OBW commented on student-work/michael-felsenthal/api-final-project/readme.md
> +
```suggestion
```

2022-04-06 16:13 UTC, Laura-Novich-OBW commented on student-work/michael-felsenthal/api-final-project/readme.md
> +[Post Reference Guide](https://github.com/Laura-Novich-OBW/student-showcase/blob/main/student-work/michael-felsenthal/api-final-project/POST.md).
```suggestion
* [Post Reference Guide](https://github.com/Laura-Novich-OBW/student-showcase/blob/main/student-work/michael-felsenthal/api-final-project/POST.md).
```

2022-04-06 16:13 UTC, Laura-Novich-OBW commented on student-work/michael-felsenthal/api-final-project/readme.md
> +
```suggestion
```

2022-04-06 16:14 UTC, Laura-Novich-OBW commented
@michaelfelsenthal please make the suggested changes plus the changes in my comments.

2022-04-06 16:28 UTC, Laura-Novich-OBW requested changes
please remove the empty lines which are all over this file.
If you want some white space one or two lines is fine.
In your code sample, however, there cannot be any empty lines.

2022-04-07 03:40 UTC, michaelfelsenthal commented
All changes implemented.

2022-04-07 05:30 UTC, closed without merging