Create get-reference-guide.md
Laura-Novich-OBW/student-showcase pull request #47
Opened 2022-04-21 07:20 UTC by JoeWainer

2022-04-21 07:29 UTC, Laura-Novich-OBW requested changes
small change
please use straight quotes for all code example values.

2022-04-21 07:29 UTC, Laura-Novich-OBW commented on student-work/joe-wainer/api-final-project/get-reference-guide.md
> +```json
```suggestion
```http
```

2022-04-21 09:36 UTC, JoeWainer reviewed
changed quotation marks

2022-04-29 05:49 UTC, Laura-Novich-OBW approved these changes

2022-04-29 05:49 UTC, merged