Create post-reference-guide.md
Laura-Novich-OBW/student-showcase pull request #48
Opened 2022-04-21 07:21 UTC by JoeWainer

2022-04-21 07:23 UTC, Laura-Novich-OBW commented on student-work/joe-wainer/api-final-project/post-reference-guide.md
> +curl -H "Content-Type: application/json" -X POST -d'{
```suggestion
{
```

2022-04-21 07:23 UTC, Laura-Novich-OBW commented on student-work/joe-wainer/api-final-project/post-reference-guide.md
> +}'
```suggestion
}
```

2022-04-21 07:24 UTC, Laura-Novich-OBW commented on student-work/joe-wainer/api-final-project/post-reference-guide.md
> +```json
```suggestion
```http
```

2022-04-21 07:25 UTC, Laura-Novich-OBW commented on student-work/joe-wainer/api-final-project/post-reference-guide.md
> +| pattyType | The type of patty. Either “beef”, “chicken”, “vegetarian”. | beef | string | Yes |
For all cases use straight quotes for the choices.
For example,
``beef`` vs "beef"

2022-04-21 07:27 UTC, Laura-Novich-OBW requested changes
changes within

2022-04-21 09:29 UTC, JoeWainer reviewed
changed quotation marks to straight

2022-04-29 05:49 UTC, Laura-Novich-OBW approved these changes

2022-04-29 05:49 UTC, merged