Update ReadMe.md
Laura-Novich-OBW/student-showcase pull request #97
Opened 2022-11-17 13:10 UTC by mindys360

DRAFT
Added CV info. Still needs editing.

2022-11-17 13:10 UTC, mindys360 commented
Entered info. Needs editing and formatting.

2022-11-19 18:28 UTC, Laura-Novich-OBW commented
Do you want me to merge it as is and you can submit another PR with changes?

2022-11-21 13:51 UTC, Laura-Novich-OBW requested changes
some small changes, but otherwise a NICE job!

2022-11-21 13:51 UTC, Laura-Novich-OBW commented on student-work/2022/Mindy-Steen/ReadMe.md
> +Aug 2015 - Dec 2018 ·
```suggestion
Aug 2015 - Dec 2018
```

2022-11-21 13:51 UTC, Laura-Novich-OBW commented on student-work/2022/Mindy-Steen/ReadMe.md
> +April 2015 - Present
```suggestion
April 2015 &ndash; Present
```

2022-11-21 13:51 UTC, Laura-Novich-OBW commented on student-work/2022/Mindy-Steen/ReadMe.md
> +Jun 2009 - Jun 2011
```suggestion
Jun 2009 &ndash;  Jun 2011
```

2022-11-21 13:51 UTC, Laura-Novich-OBW commented on student-work/2022/Mindy-Steen/ReadMe.md
> +Jun 2011 - Jun 2012
```suggestion
Jun 2011 &ndash;  Jun 2012
```

2022-11-24 14:34 UTC, mindys360 commented
Committed all suggested changes. Thank you.

2022-11-30 16:08 UTC, Laura-Novich-OBW approved these changes
Great job!

2022-11-30 16:08 UTC, merged